const EVENT = {
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',
  EVENT_CREATE_FAILURE: 'EVENT_CREATE_FAILURE',

  EVENT_LIST: 'EVENT_LIST',
  EVENT_LIST_SUCCESS: 'EVENT_LIST_SUCCESS',
  EVENT_LIST_FAILURE: 'EVENT_LIST_FAILURE',
};

export default EVENT;