const EVENT = {
  EVENT_CREATE: 'EVENT_CREATE',
  EVENT_CREATE_SUCCESS: 'EVENT_CREATE_SUCCESS',
  EVENT_CREATE_FAILURE: 'EVENT_CREATE_FAILURE',

  EVENT_LIST: 'EVENT_LIST',
  EVENT_LIST_SUCCESS: 'EVENT_LIST_SUCCESS',
  EVENT_LIST_FAILURE: 'EVENT_LIST_FAILURE',

  EVENT_LIST_NEW: 'EVENT_LIST_NEW',
  EVENT_LIST_NEW_SUCCESS: 'EVENT_LIST_NEW_SUCCESS',
  EVENT_LIST_NEW_FAILURE: 'EVENT_LIST_NEW_FAILURE',

  EVENT_LIKE: 'EVENT_LIKE',
  EVENT_LIKE_SUCCESS: 'EVENT_LIKE_SUCCESS',
  EVENT_LIKE_FAILURE: 'EVENT_LIKE_FAILURE',

  EVENT_PROFILE: 'EVENT_PROFILE',
  EVENT_PROFILE_SUCCESS: 'EVENT_PROFILE_SUCCESS',
  EVENT_PROFILE_FAILURE: 'EVENT_PROFILE_FAILURE',

  EVENT_EDIT_PROFILE: 'EVENT_EDIT_PROFILE',
  EVENT_EDIT_PROFILE_SUCCESS: 'EVENT_EDIT_PROFILE_SUCCESS',
  EVENT_EDIT_PROFILE_FAILURE: 'EVENT_EDIT_PROFILE_FAILURE',
};

export default EVENT;