const EVENTS = {
  EVENTS_CREATE: 'EVENTS_CREATE',
  EVENTS_CREATE_SUCCESS: 'EVENTS_CREATE_SUCCESS',
  EVENTS_CREATE_FAILURE: 'EVENTS_CREATE_FAILURE',

  EVENTS_LIST: 'EVENTS_LIST',
  EVENTS_LIST_SUCCESS: 'EVENTS_LIST_SUCCESS',
  EVENTS_LIST_FAILURE: 'EVENTS_LIST_FAILURE',
};

export default EVENTS;